<img src="https://github.com/nicholasmetherall/digital-earth-pacific-macblue-activities/blob/main/attachments/images/DE_Pacific_banner.JPG?raw=true" width="900"/>

Figure 1.1.a. Jupyter environment + Python notebooks

# Digital Earth Pacific Notebook 1C: use csv file to train ML model and test accuracy

The objective of this notebook is to prepare a geomad postcard for your AOI (masking, scaling and loading additional band ratios and spectral indices) and sampling all the datasets into a csv based on your training data geodataframe.

## Step 1.1: Configure the environment

In [4]:
from datetime import datetime
import geopandas as gpd
import numpy as np
import pandas as pd
import joblib
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split

<font color='red'>1.1. Input your initials and site name below. Consider how this should align with the files you are trying to open:

In [5]:
initials = "nm"
site = "rakiraki"
filename = f"{site}-tdata.csv"
version = f"{initials}-lulc-{site}"

### Postcard csv

The objective of this notebook was to train the machine learning model that will allow us to classify an area with land cover classes defined through the training data.

<font color='red'> Step 1.2. Input the training data to sample geomad data from the postcard... insert the variable `filename`

In [6]:
joined_df = gpd.read_file(f"training-data/{filename}")
joined_df

,Marine_code,nir,red,blue,green,emad,smad,bcmad,nir08,nir09,...,swir22_swir16,mci,ndci,nbi,ndmi,bsi,awei,tc_wetness,y,x
0,1.0,0.1078,0.13040000000000002,0.1208,0.14250000000000002,0.18664694,3.9926113e-06,2.221287e-05,0.0916,0.061500000000000006,...,0.6909620991253644,0.9166666666666666,-0.05161290322580647,-0.2222222222222222,0.2222222222222222,-0.12500000000000003,0.2243000000000001,0.10079834000000006,-1947955.0,3133835.0
1,1.0,0.1107,0.1386,0.13140000000000002,0.15410000000000001,0.23418245,3.165072e-06,2.4238683e-05,0.11,0.069,...,0.6877323420074349,0.7952586206896551,0.002159827213822956,-0.1567398119122257,0.1567398119122257,-0.11004126547455305,0.24342500000000006,0.11014068000000006,-1947965.0,3133905.0
2,1.0,0.1102,0.1378,0.1327,0.15430000000000002,0.22628662,3.0327021e-06,2.2525548e-05,0.10980000000000001,0.0776,...,0.6948748510131109,0.7905308464849355,0.005772005772005737,-0.1354971664090675,0.1354971664090675,-0.10660592255125287,0.24187500000000006,0.10768205000000004,-1947975.0,3133915.0
3,1.0,0.11,0.13620000000000002,0.12510000000000002,0.14930000000000002,0.22044267,4.144907e-06,2.4891084e-05,0.1019,0.0609,...,0.6865482233502538,0.8403361344537814,-0.0198427555222763,-0.16525423728813554,0.16525423728813554,-0.10531264692054537,0.22867500000000007,0.10395625000000003,-1947945.0,3133835.0
4,1.0,0.10600000000000001,0.12940000000000002,0.1217,0.14300000000000002,0.21166986,3.2086043e-06,2.5620853e-05,0.1013,0.0601,...,0.6970091027308192,0.8326787117046348,-0.008180755746007082,-0.15910333515582284,0.15910333515582284,-0.10883856829802771,0.2182500000000001,0.09903129999999999,-1947935.0,3133795.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
457,7.0,0.0246,0.027,0.0521,0.0359,0.07311736,5.28754e-06,4.1739746e-05,0.024300000000000002,0.0303,...,0.8888888888888888,0.8848920863309352,0.01459854014598544,-0.006134969325153337,0.006134969325153337,-0.22426177174780523,0.07390000000000001,0.019983600000000008,-1951435.0,3154525.0
458,7.0,0.021500000000000002,0.023200000000000002,0.0455,0.031100000000000003,0.059092563,5.2341757e-06,4.12625e-05,0.0212,0.0219,...,0.8857142857142858,0.9071729957805907,0.01066098081023455,-0.011764705882352951,0.011764705882352951,-0.2316176470588235,0.06415000000000001,0.017216570000000007,-1946615.0,3154405.0
459,7.0,0.020800000000000003,0.023200000000000002,0.046900000000000004,0.031200000000000002,0.05586934,4.3649256e-06,3.7012294e-05,0.0207,0.023200000000000002,...,0.9310344827586206,0.912280701754386,-0.008695652173913066,-0.01216545012165451,0.01216545012165451,-0.23315118397085619,0.06797500000000001,0.017129709999999996,-1948425.0,3153795.0
460,7.0,0.0198,0.0217,0.0407,0.027800000000000002,0.053515695,4.6896844e-06,3.7657188e-05,0.0212,0.0245,...,0.9330143540669855,0.868421052631579,0.024719101123595513,0.027027027027027035,-0.027027027027027035,-0.18977384464110125,0.054025000000000004,0.01412564,-1940995.0,3155105.0
461,7.0,0.0222,0.0244,0.0466,0.0317,0.05902102,5.668878e-06,3.778747e-05,0.0228,0.028300000000000002,...,0.9162995594713657,0.8705882352941177,0.02204408817635271,0.011135857461024508,-0.011135857461024508,-0.20701754385964907,0.0637,0.016940879999999995,-1942515.0,3154015.0

In [7]:
joined_df = joined_df.astype("float32")

<font color='red'>1.2. Delete the columns that you will not need including y and x by inputting them below: 
>joined_df=joined_df.drop(columns=["`...`", "`...`"])

In [8]:
joined_df=joined_df.drop(columns=["x", "y"])

<font color='red'>1.3. Print the length or number of columns using variable.columns of the new dataset.
>print(len(`variable`.`...`))

<font color='red'> Is this the same as the original file 'tdata' from notebook 1A? Why do you think the length has changed? Include your answer below and we will check it.

In [ ]:
#

<font color='red'>1.4. Print the variable.columns of the new dataset: 
>`variable`.columns

<font color='red'>1.5. Run the machine learning on your joined_df variable data: 
>training_data, test_data = train_test_split(`variable`, test_size=0.2, random_state=1337)

In [9]:
training_data, test_data = train_test_split(joined_df, test_size=0.2, random_state=1337)

<font color='red'>1.5. Run the machine learning on your `training_data` variable by replacing `insertvariable` below: 
>training_data, test_data = train_test_split(`insertvariable`, test_size=0.2, random_state=1337)

In [11]:
training_data, test_data = train_test_split(training_data, test_size=0.2, random_state=1337)

<font color='red'> Replace `insertvariable` below:

In [13]:
# The classes are the first column
classes = np.array(training_data)[:, 0]

# The observation data is everything after the second column
observations = np.array(training_data)[:, 1:]

# Create a model...
classifier = RandomForestClassifier(max_depth=4)

# ...and fit it to the data
model = classifier.fit(observations, classes)

<font color='red'>1.6. Export the model file

In [14]:
# Dynamically create the filename with f-string
file_path = f"models/{version}-test.model"

# Save the model
joblib.dump(model, file_path)

['models/nm-lulc-rakiraki-test.model']

<font color='red'>1.6. Complete a confusion matrix and display it. Discuss what this might mean with the person next to you.

In [15]:
import pandas as pd
test_actual = np.array(test_data)[:, 0]

test_predicted = model.predict(np.array(test_data)[:,1:])


unique_labels = sorted(np.unique(np.concatenate([np.asarray(test_actual), np.asarray(test_predicted)])))


pd.crosstab(test_actual, test_predicted, margins=True)

col_0  1.0  3.0  5.0  7.0  All
row_0
1.0      1    0    0    0    1
3.0      0   11    4    1   16
5.0      0    1   25    0   26
6.0      0    5    0    0    5
7.0      0    0    1   10   11
All      1   17   30   11   59

<font color='red'>1.6. Complete an accuracy score and display it. Discuss what this might mean with the person next to you.

In [16]:
from sklearn.metrics import accuracy_score

accuracy_score(test_actual, test_predicted)

0.7966101694915254

<font color='red'>1.7. Do you think this is a good accuracy score? What might be some of the reasons for lower scores? What could have been done to improve upon the accuracy?